config/routes.rb
Rails.application.routes.draw do
  resources :conversations do
    resources :messages, only: [:index, :new, :create, :destroy]
  end

  get '/conversations/:id/refresh_messages', to: 'conversations#refresh_messages', as: 'refresh_messages'
  devise_for :users
  root to: 'conversations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user1, :class_name => "User", :foreign_key => "user_1_id"
  belongs_to :user2, :class_name => "User", :foreign_key => "user_2_id"
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, :class_name => "User", :foreign_key => "user_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :conversations
  has_many :sent_messages, :class_name => "Message", :foreign_key => "user_1_id"
  has_many :received_messages, :class_name => "Message", :foreign_key => "user_2_id", through: :conversations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy, :refresh_messages]
  helper_method :recipient

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.where("user_1_id = ? or user_2_id = ?", current_user.id, current_user.id)
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
    @message = Message.new
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
    @conversation.user1 = current_user
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new()

    @conversation.user1 = current_user
    @conversation.user2 = User.find(conversation_params[:user2].to_i)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
    end
  end

  def refresh_messages
    if !params[:last_message_id].nil? &&
      last_message = @conversation.messages.find(params[:last_message_id])
      @messages = @conversation.messages.where("created_at > ?", last_message.created_at)
      respond_to do |format|
        format.js
      end
    end
  end

  def recipient(conversation)
    recipient = current_user == conversation.user1 ? conversation.user2 : conversation.user1
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:user2)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_conversation, only: [:new, :create]

  # GET /messages/new
  def new
    @message = Message.new
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    @message.conversation_id = @conversation.id

    if @message.save!
      respond_to do |format|
        format.js
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def set_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:conversation, :content, :conversation_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/_form.html.erb
<%= simple_form_for(@conversation) do |f| %>
  <%= f.error_notification %>

  <%= f.input :user2, collection: User.all.map{ |u| [u.email, u.id, { class: u.id}] } %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Conversations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= link_to conversation do %>
            Conversation with <%= recipient(conversation).email %>
            <% end %>
        </td>
        <td><%= link_to conversation, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/refresh_messages.js.erb
<% if !@messages.nil? %>
  <% @messages.each do |message| %>
    var msg_selector = $("#message_<%= message.id %>");
    $(msg_selector).remove();
    var msg = "<%= j render 'messages/show', message: message %>";
    $('#messages-list').append(msg);
  <% end %>
<% end %>

app/views/conversations/show.html.erb
<div class="container" id="messages-list" >
  <% @conversation.messages.each do |message| %>
    <%= render "messages/show", message: message %>
  <% end %>
</div>

<%= simple_form_for [@conversation, @message], :url => conversation_messages_path(@conversation), html: { id: "newMessage", class: "chat-form fixed bottom"}, method: "post", remote: true do |f| %>
    <%= f.text_field :content, id: "chat-field" %>
    <%= f.hidden_field :user_id, value: "current_user.id" %>
    <%= f.hidden_field :conversation_id, value: params[:conversation_id] %>
    <%= f.submit "Send", class: "btn btn-chat"%>
<% end %>

<%= link_to 'Back', conversations_path %>

<%= content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      scrollToBottom();
      setInterval(refreshMessages, 1000);
    });
    function scrollToBottom(){
      var d = $('#messages-list');
      d.scrollTop(d.prop("scrollHeight"));
    }
    function refreshMessages() {
      if($("#messages-list .message").length > 0) {
        var lastMessage = $("#messages-list .message").last().data("messageId");
        $.ajax({
          url: "<%= j refresh_messages_path(@conversation) %>",
          data: {last_message_id: lastMessage},
        });
      } else {
        $.ajax({
          url: "<%= j refresh_messages_path(@conversation) %>",
        });
      }
      scrollToBottom();
    }
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for [@conversation, @message] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/_show.html.erb
<% if current_user.id == message.user_id then status = "sent" else status = "received" end %>

  <div class="message <%= status %>" data-message-id="<%= message.id %>">

  <p><%=  message.content %></p>

</div>

app/views/messages/create.js.erb
$("#newMessage input").val('');

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>